/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package archivo;

import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.FileInputStream;
import java.util.Properties;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JLayeredPane;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author MONGE
 */
public class Registrar extends javax.swing.JDialog {

    /**
     * Creates new form Registrar
     */
    String barra=File.separator;
    String ruta=System.getProperty("user.dir")+barra+"registros"+barra;
    
    
    public Registrar(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
         setLocationRelativeTo(null);
         
    }
    public void validar(JTextField campo){
        String cadena=campo.getText();
        int cont=cadena.length();
        if(cont>3){
            JOptionPane.showMessageDialog(rootPane,"solo se permiten 3 letras");
        }
        else if(cadena.equals("a") ||cadena.equals("e")||cadena.equals("i")||cadena.equals("o")||cadena.equals("u") ){
            JOptionPane.showMessageDialog(rootPane,"no se permiten vocales");
        }
    }
    public void validarn(JTextField campo){
        
        String cadena=campo.getText();
        int cont=cadena.length();
        if(!cadena.equals("0") ||!cadena.equals("1" ) ||!cadena.equals("2")||!cadena.equals("3")||!cadena.equals("4")||!cadena.equals("5")||!cadena.equals("6")||!cadena.equals("7")||!cadena.equals("8")||!cadena.equals("9")){
            
        }else if(cont>3){
            JOptionPane.showMessageDialog(rootPane,"no se permiten 3 numeros");
        }
    }
    public void crear(){
        Contenido co=new Contenido();
        String placa=jtxtPlaca.getText()+".registros";
        validar(jtxtPlaca);
        co.setPlaca(placa);
        co.getPlaca();
       
        String modelo=jtxtModelo.getText();
        co.setModelo(modelo);
        co.getModelo();
        String velocidad=jtxtVelocidad.getText();
        co.setVel(velocidad);
        co.getVel();
        String marca=jtxtMarca.getText();
        co.setMarca(marca);
        co.getMarca();
        String color=jtxtColor.getText();
        co.setColor(color);
        co.getColor();
        co.setRuta(ruta);
        co.setArchivo(placa);
        co.getRuta();
        co.getArchivo();
        co.Crear();
        //
       
    }
    public void mostrar(){
        File url = new File(ruta+jtxtPlaca.getText()+".registros");
        if(url.exists()){
            
            try{
                FileInputStream fil=new FileInputStream(url);
                Properties mostrar=new Properties();
                mostrar.load(fil);
                jtxtPlaca.setText(mostrar.getProperty("placa"));
                jtxtModelo.setText(mostrar.getProperty("modelo"));
                jtxtVelocidad.setText(mostrar.getProperty("velocidad"));
                jtxtMarca.setText(mostrar.getProperty("marca"));
                jtxtColor.setText(mostrar.getProperty("color"));
            }catch(Exception e){
                
            }
        }else{
            JOptionPane.showMessageDialog(rootPane,"no existe vehiculo con esta placa");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtxtPlaca = new javax.swing.JTextField();
        jtxtModelo = new javax.swing.JTextField();
        jtxtVelocidad = new javax.swing.JTextField();
        btnRegistrar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        btnMostrar = new javax.swing.JButton();
        jComboBox = new javax.swing.JComboBox<>();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jtxtMarca = new javax.swing.JTextField();
        jtxtColor = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jtxtPlaca2 = new javax.swing.JTextField();
        fondo3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Placa");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 49, -1, -1));

        jLabel2.setText("Modelo");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 89, -1, -1));

        jLabel3.setText("velocidad");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 129, -1, -1));
        getContentPane().add(jtxtPlaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 43, 107, -1));
        getContentPane().add(jtxtModelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 83, 107, -1));
        getContentPane().add(jtxtVelocidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 123, 107, -1));

        btnRegistrar.setText("Registrar");
        btnRegistrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegistrarMouseClicked(evt);
            }
        });
        getContentPane().add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, -1, -1));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Si el vehiculo ya esta registrado, digite la placa y luego de clic en mostrar");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 400, -1));

        btnMostrar.setText("Mostrar");
        btnMostrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMostrarMouseClicked(evt);
            }
        });
        getContentPane().add(btnMostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 281, -1, -1));

        jComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "100", "150", "200", " ", " " }));
        jComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 124, -1, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "23", "12", "15" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(313, 124, -1, -1));

        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("deportivo");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 101, -1, -1));

        jLabel6.setForeground(new java.awt.Color(255, 0, 0));
        jLabel6.setText("furgoneta");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(313, 101, -1, -1));
        getContentPane().add(jtxtMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 157, 107, -1));
        getContentPane().add(jtxtColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 191, 107, -1));

        jLabel7.setText("marca");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 169, -1, -1));

        jLabel8.setText("color");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 197, -1, -1));
        getContentPane().add(jtxtPlaca2, new org.netbeans.lib.awtextra.AbsoluteConstraints(177, 43, 98, -1));

        fondo3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/lam.jpg"))); // NOI18N
        getContentPane().add(fondo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-100, -10, 520, 330));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistrarMouseClicked
        // TODO add your handling code here:
        crear();
        
    }//GEN-LAST:event_btnRegistrarMouseClicked
//
    private void btnMostrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMostrarMouseClicked
        // TODO add your handling code here:
        mostrar();
        
    }//GEN-LAST:event_btnMostrarMouseClicked

    private void jComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxActionPerformed
        // TODO add your handling code here:
        Contenido co=new Contenido();
        int i=jComboBox.getSelectedIndex();
       if(i==0){
          
           jtxtVelocidad.setText("100");
           String a=jtxtVelocidad.getText();
           co.setVel(a);
           co.getVel();
           
        }else if(i==1){
            
           jtxtVelocidad.setText("150");
           String a = jtxtVelocidad.getText();
           co.setVel(a);
           co.getVel();
            
        }else if(i==2){
           jtxtVelocidad.setText("200");
           String a = jtxtVelocidad.getText();
           co.setVel(a);
           co.getVel();
        }
    }//GEN-LAST:event_jComboBoxActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        Contenido co=new Contenido();
        int i=jComboBox1.getSelectedIndex();
        // TODO add your handling code here:
        if(i==0){
           jtxtVelocidad.setText("23=disponible");
           String a = jtxtVelocidad.getText();
           co.setVel(a);
           co.getVel();
        }else if(i==1){
            
            JOptionPane.showMessageDialog(rootPane,"lo sentimos esta capacidad no esta disponible");
            
            
        }else if(i==2){
           jtxtVelocidad.setText("15=disponible");
           String a = jtxtVelocidad.getText();
           co.setVel(a);
           co.getVel();
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Registrar dialog = new Registrar(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMostrar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JLabel fondo3;
    private javax.swing.JComboBox<String> jComboBox;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jtxtColor;
    private javax.swing.JTextField jtxtMarca;
    private javax.swing.JTextField jtxtModelo;
    private javax.swing.JTextField jtxtPlaca;
    private javax.swing.JTextField jtxtPlaca2;
    private javax.swing.JTextField jtxtVelocidad;
    // End of variables declaration//GEN-END:variables
}
