/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package archivo;

import java.awt.TextArea;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JLayeredPane;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author estudiante
 */
public class VerMarcas extends javax.swing.JDialog {

    /**
     * Creates new form VerMarcas
     */
    public VerMarcas(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        
    }
    public void Larchivo(){
         
         String ver="";
        try {
            FileReader archivo1 = new FileReader("Lista.txt");
            BufferedReader br = new BufferedReader(archivo1);
            String cadena;
            while ((cadena = br.readLine()) != null) {
//               System.out.println("" + cadena);
                 ver=this.jtxtVer.getText();
                 this.jtxtVer.setText(""+cadena);
               
            }
            archivo1.close();
        } catch (Exception ex) {

        }
        
    }
    public void mod() throws IOException{
        String a="";
        a=jtxtEs.getText();
        Contenido co =new Contenido();
        Logica lo =new Logica();
        lo.setMarca(a);
        lo.getMarca();
        co.Emarcas();
        co.Earchivo();
    }
    

    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAñadir = new javax.swing.JButton();
        btnVermarcas = new javax.swing.JButton();
        btnVerc = new javax.swing.JButton();
        jtxtVer = new javax.swing.JTextField();
        jtxtEs = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        fondo2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAñadir.setText("Añadir marca");
        btnAñadir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAñadirMouseClicked(evt);
            }
        });
        getContentPane().add(btnAñadir, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, -1, -1));

        btnVermarcas.setText("ver Marcas");
        btnVermarcas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVermarcasMouseClicked(evt);
            }
        });
        btnVermarcas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVermarcasActionPerformed(evt);
            }
        });
        getContentPane().add(btnVermarcas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, -1, -1));

        btnVerc.setText("ver colores");
        getContentPane().add(btnVerc, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, -1, -1));

        jtxtVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtVerActionPerformed(evt);
            }
        });
        getContentPane().add(jtxtVer, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 361, 143));
        getContentPane().add(jtxtEs, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 220, 94, -1));

        jLabel1.setText("Para terminar de añadir marcas digite \"a\" y añadir");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 288, -1));

        fondo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/ccc.jpg"))); // NOI18N
        getContentPane().add(fondo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-100, 0, 550, 310));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVermarcasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVermarcasMouseClicked
        // TODO add your handling code here:
       
        
                Larchivo();
        
       
       
        
    }//GEN-LAST:event_btnVermarcasMouseClicked

    private void btnVermarcasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVermarcasActionPerformed
        // TODO add your handling code here:
        
       
    }//GEN-LAST:event_btnVermarcasActionPerformed

    private void btnAñadirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAñadirMouseClicked
        try {
            mod();
        } catch (IOException ex) {
            Logger.getLogger(VerMarcas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnAñadirMouseClicked

    private void jtxtVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtVerActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jtxtVerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VerMarcas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VerMarcas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VerMarcas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VerMarcas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VerMarcas dialog = new VerMarcas(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAñadir;
    private javax.swing.JButton btnVerc;
    private javax.swing.JButton btnVermarcas;
    private javax.swing.JLabel fondo2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jtxtEs;
    private javax.swing.JTextField jtxtVer;
    // End of variables declaration//GEN-END:variables
}
