/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Empresa;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author estudiante
 */
public class Producto extends javax.swing.JDialog {

    /**
     * Creates new form Fresco
     */
    int i;
    public Producto(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
         setLocationRelativeTo(null);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtxtDia = new javax.swing.JTextField();
        jtxtMes = new javax.swing.JTextField();
        jtxtAño = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jtxtPais = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jtxtLote = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jtxtTipo = new javax.swing.JTextField();
        jComboTipo = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jtxtDia2 = new javax.swing.JTextField();
        jtxtMes2 = new javax.swing.JTextField();
        jtxtAño2 = new javax.swing.JTextField();
        btnNext = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jtxtCodigo = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtxtDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtDiaActionPerformed(evt);
            }
        });
        jtxtDia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtDiaKeyTyped(evt);
            }
        });
        getContentPane().add(jtxtDia, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 38, -1));

        jtxtMes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtMesKeyTyped(evt);
            }
        });
        getContentPane().add(jtxtMes, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, 42, -1));

        jtxtAño.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtAñoKeyTyped(evt);
            }
        });
        getContentPane().add(jtxtAño, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, 43, -1));

        jLabel1.setText("dd");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, -1, -1));

        jLabel2.setText("mm");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, -1, -1));

        jLabel3.setText("mmmm");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, -1, -1));

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 0, 10)); // NOI18N
        jLabel4.setText("ingrese Fecha de caducidad");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 143, -1));

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        jLabel5.setText("Pais origen");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 133, -1));
        getContentPane().add(jtxtPais, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 146, -1));

        jLabel6.setText("Lote");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));
        getContentPane().add(jtxtLote, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 146, -1));

        jLabel7.setText("Tipo");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 20, -1, -1));

        jtxtTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtTipoActionPerformed(evt);
            }
        });
        getContentPane().add(jtxtTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 135, -1));

        jComboTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Frescos", "Refrigerados", "Congelados", " " }));
        jComboTipo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboTipoMouseClicked(evt);
            }
        });
        jComboTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboTipoActionPerformed(evt);
            }
        });
        getContentPane().add(jComboTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(298, 20, -1, -1));

        jLabel8.setText("Ingrese fecha de envasado");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, 20));
        getContentPane().add(jtxtDia2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 36, -1));
        getContentPane().add(jtxtMes2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, 47, -1));
        getContentPane().add(jtxtAño2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 220, 52, -1));

        btnNext.setText("next");
        btnNext.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNextMouseClicked(evt);
            }
        });
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });
        getContentPane().add(btnNext, new org.netbeans.lib.awtextra.AbsoluteConstraints(354, 277, -1, -1));

        jLabel11.setText("dd");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, -1, -1));

        jLabel12.setText("mm");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, -1, -1));

        jLabel10.setText("Codigo de supervision");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, -1, -1));

        jLabel13.setText("mmmm");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, -1, -1));
        getContentPane().add(jtxtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, 140, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/fruta.jpg"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtDiaActionPerformed
        // TODO add your handling code here:
         

    }//GEN-LAST:event_jtxtDiaActionPerformed

    private void jtxtDiaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtDiaKeyTyped
        // TODO add your handling code here:
        
        {
            if (jtxtDia.getText().length() == 2 ||jtxtDia2.getText().length() == 2 ) {
                evt.consume();
            }
        }
        char car = evt.getKeyChar();
        if (Character.isDigit(car)) {

        } else {
            evt.consume();
            getToolkit().beep();
        }
    }//GEN-LAST:event_jtxtDiaKeyTyped

    private void jtxtMesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtMesKeyTyped
        // TODO add your handling code here:
        {
            if (jtxtMes.getText().length() == 2 || jtxtMes2.getText().length() == 2) {
                evt.consume();
            }
        }
        char car = evt.getKeyChar();
        if (Character.isDigit(car)) {

        } else {
            evt.consume();
            getToolkit().beep();
        }
    }//GEN-LAST:event_jtxtMesKeyTyped

    private void jtxtAñoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtAñoKeyTyped
        // TODO add your handling code here:
        {
            if (jtxtAño.getText().length() == 4 || jtxtAño2.getText().length() == 4 ) {
                evt.consume();
            }
        }
        char car = evt.getKeyChar();
        if (Character.isDigit(car)) {

        } else {
            evt.consume();
            getToolkit().beep();
        }
    }//GEN-LAST:event_jtxtAñoKeyTyped

    private void jComboTipoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboTipoMouseClicked
       
    }//GEN-LAST:event_jComboTipoMouseClicked

    private void jComboTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboTipoActionPerformed
        // TODO add your handling code here:
         i=jComboTipo.getSelectedIndex();
         String tipo=jtxtTipo.getText();
       if(i==0){
            tipo="Frescos";
            jtxtPais.setEditable(true);
            jtxtCodigo.setEditable(false);
            btnNext.setVisible(false);
        }else if(i==1){
            
            tipo="Refrigerados";
            jtxtPais.setEditable(false);
            jtxtCodigo.setEditable(true);
            btnNext.setVisible(false);
//            jtxtPais.setEnabled(false); 
        }else if(i==2){
            
           
           tipo="Congelados";
           jtxtPais.setEditable(false);
           jtxtCodigo.setEditable(false);
           btnNext.setVisible(true);
           
           
        }
        jtxtTipo.setText(tipo);
      
    
    }//GEN-LAST:event_jComboTipoActionPerformed

    public int getI() {
        return i;
    }
    
    private void jtxtTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtTipoActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnNextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNextMouseClicked
         
        Producto2 ventana2 = new Producto2 (null, true);
        ventana2.pack();
        ventana2.setVisible(true);
        
    }//GEN-LAST:event_btnNextMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Producto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Producto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Producto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Producto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Producto dialog = new Producto(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNext;
    private javax.swing.JComboBox<String> jComboTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jtxtAño;
    private javax.swing.JTextField jtxtAño2;
    private javax.swing.JTextField jtxtCodigo;
    private javax.swing.JTextField jtxtDia;
    private javax.swing.JTextField jtxtDia2;
    private javax.swing.JTextField jtxtLote;
    private javax.swing.JTextField jtxtMes;
    private javax.swing.JTextField jtxtMes2;
    private javax.swing.JTextField jtxtPais;
    private javax.swing.JTextField jtxtTipo;
    // End of variables declaration//GEN-END:variables
}
